apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "json-log-generator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "json-log-generator.name" . }}
    {{- with .Values.podLabels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "json-log-generator.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "json-log-generator.name" . }}
        {{- with .Values.podLabels }}
        {{ toYaml . | indent 8 }}
        {{- end }}
    spec:
      containers:
        - name: json-log-generator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # Logs output to stdout, no ports needed
