apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "json-log-generator.fullname" . }}
  labels:
    {{- include "json-log-generator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "json-log-generator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "json-log-generator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
